export const legalDomain = {
  legal: {
    back: 'Back',
    language: 'Language',
    pt: 'PT',
    en: 'EN',
    es: 'ES',
    terms: {
      title: 'Terms of Use',
      sections: {
        purpose: {
          title: '1. Platform purpose',
          body: 'Skill Refine is a platform that uses artificial intelligence to analyze resumes and provide personalized improvement suggestions. The service aims to help professionals optimize their resumes for job opportunities.',
        },
        rules: {
          title: '2. Rules of use and user responsibility',
          body: 'The user is responsible for providing true and up-to-date information. It is prohibited to use the platform for illegal, defamatory purposes or that violate third-party rights. The user must maintain the confidentiality of their account and password.',
        },
        ip: {
          title: '3. Intellectual property',
          body: 'Content created by the user (resumes, texts) remains their property. Skill Refine holds the rights to the platform, brand, interface and technologies used. Use of the service does not transfer any intellectual property rights to the user.',
        },
        liability: {
          title: '4. Limitation of liability',
          body: 'Skill Refine provides analyses and suggestions based on AI, which do not constitute legal or professional advice. The platform is not responsible for decisions made based on the analyses. The service is provided "as is", within applicable technical limitations.',
        },
        suspension: {
          title: '5. Suspension, ban and deletion',
          body: 'The platform reserves the right to suspend or terminate accounts in case of violation of these terms, misuse or for operational reasons. The user may request deletion of their account at any time.',
        },
      },
    },
    privacy: {
      title: 'Privacy Policy',
      sections: {
        dataCollected: {
          title: '1. Data collected',
          body: 'We collect account data (name, email, date of birth), resumes submitted, analyses generated by AI, theme preferences and platform settings. Usage data and technical logs may be recorded for service operation and improvement.',
        },
        purpose: {
          title: '2. Purpose of processing',
          body: 'Data is used to provide and personalize the resume analysis service, send account-related communications, improve the platform and comply with legal obligations.',
        },
        storage: {
          title: '3. Storage and retention',
          body: 'Data is stored on secure servers. Resumes and analyses are kept while the account is active. After account deletion, data is removed according to our retention policy, except when the law requires preservation.',
        },
        sharing: {
          title: '4. Sharing with third parties',
          body: 'We may use email providers for communications, cloud storage services and AI providers to process analyses. These partners are contracted under agreements that ensure data protection. We do not sell personal data.',
        },
        rights: {
          title: '5. Data subject rights',
          body: 'You have the right to access, correct, delete and request portability of your data. You may revoke consents and file complaints with the data protection authority. These rights can be exercised through account settings or by contacting support.',
        },
        security: {
          title: '6. Security',
          body: 'We adopt technical and organizational measures to protect data against unauthorized access, alteration, disclosure or destruction. Platform access uses encryption and secure authentication.',
        },
      },
    },
  },
} as const;
