import type { ResumeTheme, ResumeThemePalette } from '../model/theme';

const BASE_PALETTES: ResumeThemePalette[] = [
  { id: 'neutral', name: 'Neutro', accent: '#1F2937', accentSoft: 'rgba(31, 41, 55, 0.08)' },
  { id: 'blue', name: 'Azul', accent: '#2563EB', accentSoft: 'rgba(37, 99, 235, 0.12)' },
  { id: 'purple', name: 'Roxo', accent: '#7C3AED', accentSoft: 'rgba(124, 58, 237, 0.12)' },
  { id: 'green', name: 'Verde', accent: '#0F766E', accentSoft: 'rgba(15, 118, 110, 0.12)' },
  { id: 'mono', name: 'Monocromático', accent: '#111827', accentSoft: 'rgba(17, 24, 39, 0.12)' },
];

export const resumeThemes: ResumeTheme[] = [
  {
    id: 'classic-one-column',
    name: 'Classic One-Column',
    description: 'Layout clássico e linear, ideal para ATS.',
    tag: 'ATS-first',
    tags: ['ATS-friendly', '1 coluna'],
    category: 'Clássico',
    thumbnailSpec: { type: 'one-column', blocks: 5, header: 'simple' },
    layout: { type: 'single' },
    sectionOrder: ['summary', 'experience', 'education', 'skills', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'neutral',
    styleTokens: {
      fontFamily: '"Inter", "Segoe UI", sans-serif',
      headingFontFamily: '"Inter", "Segoe UI", sans-serif',
      spacingLg: '28px',
      spacingMd: '18px',
      spacingSm: '10px',
      sectionGap: '18px',
      radius: '6px',
    },
  },
  {
    id: 'modern-one-column',
    name: 'Modern One-Column',
    description: 'Visual moderno com leitura direta.',
    tag: 'Moderno',
    tags: ['ATS-friendly', '1 coluna'],
    category: 'Moderno',
    thumbnailSpec: { type: 'one-column', blocks: 6, header: 'hero' },
    layout: { type: 'single' },
    sectionOrder: ['summary', 'skills', 'experience', 'education', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'blue',
    styleTokens: {
      fontFamily: '"Inter", "Segoe UI", sans-serif',
      headingFontFamily: '"Inter", "Segoe UI", sans-serif',
      spacingLg: '26px',
      spacingMd: '16px',
      spacingSm: '8px',
      sectionGap: '16px',
      radius: '10px',
    },
  },
  {
    id: 'two-column-sidebar',
    name: 'Two-Column Sidebar',
    description: 'Sidebar para contato e skills (atenção ao ATS).',
    tag: '2 colunas',
    tags: ['2 colunas', 'ATS atenção'],
    category: 'Moderno',
    thumbnailSpec: { type: 'two-column', sidebarPosition: 'right', mainBlocks: 4, sidebarBlocks: 3 },
    layout: {
      type: 'split',
      sidebarPosition: 'right',
      sidebarSections: ['contact', 'skills', 'languages'],
      mainSections: ['summary', 'experience', 'education'],
    },
    sectionOrder: ['summary', 'experience', 'education', 'skills', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'green',
    styleTokens: {
      fontFamily: '"Inter", "Segoe UI", sans-serif',
      headingFontFamily: '"Inter", "Segoe UI", sans-serif',
      sidebarBg: '#F1F5F9',
      spacingLg: '24px',
      spacingMd: '16px',
      spacingSm: '8px',
      sectionGap: '16px',
      radius: '12px',
    },
  },
  {
    id: 'executive',
    name: 'Executive',
    description: 'Hierarquia sólida e tipografia séria.',
    tag: 'Executivo',
    tags: ['ATS-friendly', '1 coluna'],
    category: 'Profissional',
    thumbnailSpec: { type: 'one-column', blocks: 5, header: 'hero' },
    layout: { type: 'single' },
    sectionOrder: ['summary', 'experience', 'education', 'skills', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'neutral',
    styleTokens: {
      fontFamily: '"Libre Franklin", "Segoe UI", sans-serif',
      headingFontFamily: '"Libre Franklin", "Segoe UI", sans-serif',
      borderColor: '#CBD5E0',
      spacingLg: '26px',
      spacingMd: '16px',
      spacingSm: '8px',
      sectionGap: '16px',
      radius: '8px',
    },
  },
  {
    id: 'compact-dense',
    name: 'Compact Dense',
    description: 'Alta densidade para maximizar conteúdo.',
    tag: 'Compacto',
    tags: ['1 página', 'denso'],
    category: 'Produtividade',
    thumbnailSpec: { type: 'compact', columns: 2, blocks: 6 },
    layout: { type: 'compact', columns: 2 },
    sectionOrder: ['summary', 'experience', 'education', 'skills', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'mono',
    styleTokens: {
      fontFamily: '"Inter", "Segoe UI", sans-serif',
      headingFontFamily: '"Inter", "Segoe UI", sans-serif',
      spacingLg: '18px',
      spacingMd: '12px',
      spacingSm: '6px',
      sectionGap: '12px',
      radius: '6px',
    },
  },
  {
    id: 'timeline-experience',
    name: 'Timeline Experience',
    description: 'Experiência em linha do tempo vertical.',
    tag: 'Timeline',
    tags: ['1 coluna', 'visual'],
    category: 'Moderno',
    thumbnailSpec: { type: 'timeline', items: 4 },
    layout: { type: 'timeline' },
    sectionOrder: ['summary', 'experience', 'education', 'skills', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'blue',
    styleTokens: {
      fontFamily: '"Inter", "Segoe UI", sans-serif',
      headingFontFamily: '"Inter", "Segoe UI", sans-serif',
      spacingLg: '24px',
      spacingMd: '16px',
      spacingSm: '8px',
      sectionGap: '16px',
      radius: '10px',
    },
  },
  {
    id: 'project-first',
    name: 'Project-First',
    description: 'Projetos e cases em destaque visual.',
    tag: 'Projetos',
    tags: ['visual', 'cards'],
    category: 'Criativo',
    thumbnailSpec: { type: 'project-grid', columns: 2, rows: 2 },
    layout: { type: 'grid' },
    sectionOrder: ['summary', 'experience', 'skills', 'education', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'purple',
    styleTokens: {
      fontFamily: '"Manrope", "Segoe UI", sans-serif',
      headingFontFamily: '"Manrope", "Segoe UI", sans-serif',
      spacingLg: '22px',
      spacingMd: '14px',
      spacingSm: '8px',
      sectionGap: '14px',
      radius: '12px',
    },
  },
  {
    id: 'academic',
    name: 'Academic',
    description: 'Ênfase em formação e produção acadêmica.',
    tag: 'Acadêmico',
    tags: ['1 coluna', 'rigor'],
    category: 'Acadêmico',
    thumbnailSpec: { type: 'one-column', blocks: 6, header: 'hero' },
    layout: { type: 'single' },
    sectionOrder: ['education', 'experience', 'summary', 'skills', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'blue',
    styleTokens: {
      fontFamily: '"Merriweather", "Times New Roman", serif',
      headingFontFamily: '"Merriweather", "Times New Roman", serif',
      spacingLg: '26px',
      spacingMd: '16px',
      spacingSm: '8px',
      sectionGap: '16px',
      radius: '6px',
    },
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    description: 'Espaço em branco e leitura fluida.',
    tag: 'Minimal',
    tags: ['ATS-friendly', 'clean'],
    category: 'Minimal',
    thumbnailSpec: { type: 'one-column', blocks: 4, header: 'simple' },
    layout: { type: 'single' },
    sectionOrder: ['summary', 'experience', 'education', 'skills', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'neutral',
    styleTokens: {
      fontFamily: '"Inter", "Segoe UI", sans-serif',
      headingFontFamily: '"Inter", "Segoe UI", sans-serif',
      spacingLg: '32px',
      spacingMd: '20px',
      spacingSm: '10px',
      sectionGap: '22px',
      radius: '10px',
    },
  },
  {
    id: 'elegant-serif',
    name: 'Elegant Serif',
    description: 'Serifado com hierarquia clássica.',
    tag: 'Elegante',
    tags: ['1 coluna', 'serif'],
    category: 'Clássico',
    thumbnailSpec: { type: 'one-column', blocks: 5, header: 'hero' },
    layout: { type: 'single' },
    sectionOrder: ['summary', 'experience', 'education', 'skills', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'mono',
    styleTokens: {
      fontFamily: '"Playfair Display", "Times New Roman", serif',
      headingFontFamily: '"Playfair Display", "Times New Roman", serif',
      spacingLg: '28px',
      spacingMd: '18px',
      spacingSm: '10px',
      sectionGap: '18px',
      radius: '6px',
    },
  },
  {
    id: 'tech-stack',
    name: 'Tech Stack',
    description: 'Skills e stacks em destaque lateral.',
    tag: 'Tech',
    tags: ['2 colunas', 'skills'],
    category: 'Tecnologia',
    thumbnailSpec: { type: 'two-column', sidebarPosition: 'left', mainBlocks: 3, sidebarBlocks: 4 },
    layout: {
      type: 'split',
      sidebarPosition: 'left',
      sidebarSections: ['skills', 'languages', 'contact'],
      mainSections: ['summary', 'experience', 'education'],
    },
    sectionOrder: ['summary', 'experience', 'education', 'skills', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: [
      { id: 'blue', name: 'Azul', accent: '#0EA5E9', accentSoft: 'rgba(14, 165, 233, 0.12)' },
      { id: 'green', name: 'Verde', accent: '#10B981', accentSoft: 'rgba(16, 185, 129, 0.12)' },
      { id: 'mono', name: 'Monocromático', accent: '#E2E8F0', accentSoft: 'rgba(226, 232, 240, 0.12)' },
    ],
    defaultPaletteId: 'blue',
    styleTokens: {
      fontFamily: '"JetBrains Mono", "Inter", monospace',
      headingFontFamily: '"Inter", "Segoe UI", sans-serif',
      sidebarBg: '#0F172A',
      paperBg: '#0B1220',
      borderColor: '#1E293B',
      spacingLg: '22px',
      spacingMd: '14px',
      spacingSm: '8px',
      sectionGap: '14px',
      radius: '10px',
    },
  },
  {
    id: 'hybrid-balanced',
    name: 'Hybrid Balanced',
    description: 'Resumo, competências e experiência equilibrados.',
    tag: 'Híbrido',
    tags: ['ATS-friendly', 'equilíbrio'],
    category: 'Versátil',
    thumbnailSpec: { type: 'one-column', blocks: 6, header: 'simple' },
    layout: { type: 'single' },
    sectionOrder: ['summary', 'skills', 'experience', 'education', 'languages', 'contact'],
    visibilityRules: {
      summary: 'hideIfEmpty',
      experience: 'hideIfEmpty',
      education: 'hideIfEmpty',
      skills: 'hideIfEmpty',
      languages: 'hideIfEmpty',
      contact: 'hideIfEmpty',
    },
    palettes: BASE_PALETTES,
    defaultPaletteId: 'purple',
    styleTokens: {
      fontFamily: '"Inter", "Segoe UI", sans-serif',
      headingFontFamily: '"Inter", "Segoe UI", sans-serif',
      spacingLg: '24px',
      spacingMd: '16px',
      spacingSm: '8px',
      sectionGap: '16px',
      radius: '8px',
    },
  },
];

export const DEFAULT_RESUME_THEME_ID: ResumeTheme['id'] = 'classic-one-column';

export const getResumeThemeById = (id: ResumeTheme['id']): ResumeTheme =>
  resumeThemes.find((theme) => theme.id === id) ?? resumeThemes[0]!;

const FALLBACK_PALETTE: ResumeThemePalette = {
  id: 'neutral',
  name: 'Neutro',
  accent: '#1F2937',
  accentSoft: 'rgba(31, 41, 55, 0.08)',
};

export const getResumeThemePalette = (theme: ResumeTheme, paletteId?: string): ResumeThemePalette =>
  theme.palettes.find((palette) => palette.id === paletteId) ??
  theme.palettes.find((palette) => palette.id === theme.defaultPaletteId) ??
  theme.palettes[0] ??
  FALLBACK_PALETTE;
