# Generated by Django 5.2.9 on 2026-03-11 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("analysis_done", "analysis_done"),
                            ("analysis_failed", "analysis_failed"),
                            ("pdf_ready", "pdf_ready"),
                            ("pdf_failed", "pdf_failed"),
                            ("version_restored", "version_restored"),
                            ("system", "system"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title_key", models.CharField(blank=True, default="", max_length=120)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("entity_ref", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_notif_user_created"
                    ),
                    models.Index(
                        fields=["user", "is_read"], name="idx_notif_user_read"
                    ),
                ],
            },
        ),
    ]
