"""
As 13 categorias de domínio do produto e as pistas de palavra-chave por idioma.

Tabela, não lógica — por isso fora de ``domain_inference.py``. Vale registrar a limitação medida:
**51% das 1.701 ocupações ESCO caem em `operations`** (§6 do handoff), porque estas categorias são
de colarinho branco e jogam ofício, operação de máquina, transporte e serviço no mesmo balde. Mudar
isso altera o comprimento do one-hot em ``ml_feature_row.py`` e invalida o bundle target_fit_v1, ou
seja é mudança deliberada com retreino.
"""
from __future__ import annotations


DOMAIN_CATEGORIES: tuple[str, ...] = (
    "health",
    "education",
    "legal",
    "finance",
    "engineering",
    "marketing",
    "sales",
    "technology",
    "administrative",
    "science",
    "hr",
    "operations",
    "creative",
    "general",
)

# category -> list of lowercase tokens (any language, ASCII-folded)
_DOMAIN_KEYWORDS: dict[str, tuple[str, ...]] = {
    "health": (
        "nurse",
        "nursing",
        "enferm",
        "médic",
        "medico",
        "medicina",
        "clinic",
        "clínica",
        "hospital",
        "patient",
        "paciente",
        "saude",
        "saúde",
        "salud",
        "fisioter",
        "psicolog",
        "farmácia",
        "farmacia",
        "biomedic",
        "odont",
        "veterin",
        "cirurg",
        "therap",
        "terapia",
    ),
    "education": (
        "teacher",
        "professor",
        "profesor",
        "profesora",
        "professora",
        "educação",
        "educacion",
        "education",
        "pedagog",
        "didática",
        "school",
        "escola",
        "univers",
        "academic",
        "curriculum",
        "ensino",
        "aluno",
        "student",
        "tutor",
    ),
    "legal": (
        "lawyer",
        "advogad",
        "abogad",
        "jurid",
        "legal",
        "compliance",
        "contrato",
        "contract",
        "tribunal",
        "court",
        "litig",
        "notár",
        "notario",
    ),
    "finance": (
        "finance",
        "financ",
        "contab",
        "account",
        "auditor",
        "invest",
        "bank",
        "banco",
        "tesour",
        "fp&a",
        "budget",
        "orçamento",
        "tax",
        "fiscal",
        "risk",
        "credit",
    ),
    "engineering": (
        "engineer",
        "engenheir",
        "ingenier",
        "civil",
        "mechanical",
        "mecânico",
        "electrical",
        "elétric",
        "chemical",
        "químico",
        "industrial",
        "projeto",
        "obra",
        "automação",
        "hvac",
    ),
    "marketing": (
        "marketing",
        "brand",
        "marca",
        "growth",
        "seo",
        "sem",
        "content",
        "conteúdo",
        "social media",
        "campanha",
        "campaign",
        "crm",
        "copywrit",
    ),
    "sales": (
        "sales",
        "vendas",
        "ventas",
        "comercial",
        "account executive",
        "business development",
        "bdr",
        "sdr",
        "retail",
        "vendedor",
        "representante",
    ),
    "technology": (
        "software",
        "developer",
        "desenvolvedor",
        "programador",
        "devops",
        "data scientist",
        "cientista de dados",
        "it ",
        "ti ",
        "tech",
        "cloud",
        "aws",
        "azure",
        "kubernetes",
        "frontend",
        "backend",
        "fullstack",
        "machine learning",
        "cyber",
        "sistemas",
    ),
    "administrative": (
        "administrativ",
        "secretári",
        "secretaria",
        "assistente",
        "assistant",
        "office",
        "escritório",
        "recepção",
        "recepcion",
        "backoffice",
        "coordenação administrativa",
    ),
    "science": (
        "research",
        "pesquisa",
        "investigação",
        "laborat",
        "biolog",
        "biólog",
        "químico",
        "chemist",
        "physics",
        "físic",
        "geolog",
        "ambiental",
        "ecolog",
    ),
    "hr": (
        "human resources",
        "recursos humanos",
        "rh ",
        "people ",
        "talent",
        "recrut",
        "recruit",
        "seleção",
        "seleccion",
        "payroll",
        "folha",
        "diversidad",
    ),
    "operations": (
        "operations",
        "operações",
        "operaciones",
        "logística",
        "logistica",
        "supply chain",
        "procurement",
        "compras",
        "warehouse",
        "estoque",
        "inventory",
        "plant manager",
        "produção",
        "lean",
    ),
    "creative": (
        "design",
        "designer",
        "ux",
        "ui ",
        "illustr",
        "fotograf",
        "photograph",
        "video",
        "motion",
        "arte",
        "artíst",
        "creative",
        "creador",
    ),
}
