# Generated by Django 5.2.17 on 2026-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_resumeanalysis_ai_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='provider',
            field=models.CharField(blank=True, default='local', max_length=32),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='seniority_label_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
