# Generated by Django 5.2.9 on 2026-03-03 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_soft_delete_email_uniqueness"),
        ("resumes", "0002_resume_last_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=False)),
                ("snapshot_json", models.JSONField(default=dict)),
                ("change_summary_json", models.JSONField(default=list)),
                ("score", models.IntegerField(blank=True, null=True)),
                (
                    "resume",
                    models.ForeignKey(
                        db_column="resume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumes.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "resume_versions",
                "indexes": [
                    models.Index(
                        fields=["resume", "-version_number"],
                        name="idx_resume_versions_resume",
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="idx_resume_versions_user"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resume", "version_number"),
                        name="uniq_resume_version_number",
                    )
                ],
            },
        ),
    ]
