# Generated by Django 5.2.9 on 2026-03-05 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_soft_delete_email_uniqueness"),
        ("resumes", "0003_add_resume_versions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[("pdf", "pdf")],
                        default="pdf",
                        max_length=16,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("running", "running"),
                            ("ready", "ready"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("storage_path", models.CharField(blank=True, default="", max_length=500)),
                ("file_size_bytes", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metrics_json", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resume",
                    models.ForeignKey(
                        db_column="resume_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resumes.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "resume_exports",
                "indexes": [
                    models.Index(
                        fields=["resume", "export_type", "status"],
                        name="idx_resume_export_lookup",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="idx_resume_export_user_created",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resume", "export_type", "fingerprint"),
                        name="uniq_resume_export_fingerprint",
                    )
                ],
            },
        ),
    ]
